M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Tue Jul 30 13:46:42 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-30T13:46:42+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X8.88Y125.63
X58.88Y125.63
X85.08Y125.63
X135.08Y125.63
T0
M30
